# -*- coding: utf-8 -*-
"""proofreading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zn9ou4glW8lFutZmzJq0XWNvlpqH_el

このコードは動画から文字起こしをするコードです。
"""

#SDK install
!pip install google-genai

#import liblary
from google import genai
from google.genai import types
from google.colab import userdata

#API KEY 取得
GEMINI_API_KEY = userdata.get('GOOGLE_API_KEY')

# prompt: mount the drive
from google.colab import drive
drive.mount('/content/drive')

#APIキーのモデルへの設定
client = genai.Client(api_key=GEMINI_API_KEY)

#変数定義
#ファイルのPATH
file_path = "/content/drive/MyDrive/AIE_data/LLM2024_day2_s2t.txt"
output_file_path = "/content/drive/MyDrive/AIE_data/processed_text.txt"
prompt = "このファイルの書きおこし文をを自然な日本語に修正してください。"

#ファイルを読み込む
myfile = client.files.upload(file=file_path)

#gemini2.0で生成
response = client.models.generate_content(
    model="gemini-2.0-flash", contents=[prompt, myfile]
)

print(response.text)
#responseの内容をファイルに保存
with open(output_file_path, "w") as f:
    f.write(response.text)